//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMS.Context.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOG_APP> LOG_APP { get; set; }
        public virtual DbSet<LOG_IIS> LOG_IIS { get; set; }
        public virtual DbSet<LOG_PERSO> LOG_PERSO { get; set; }
        public virtual DbSet<LOG_PERSO_COUNT> LOG_PERSO_COUNT { get; set; }
        public virtual DbSet<LOG_USER> LOG_USER { get; set; }
        public virtual DbSet<LOG_YEAR> LOG_YEAR { get; set; }
        public virtual DbSet<M_ACCESS> M_ACCESS { get; set; }
        public virtual DbSet<M_COMPANY> M_COMPANY { get; set; }
        public virtual DbSet<M_CONFIGURATION> M_CONFIGURATION { get; set; }
        public virtual DbSet<M_CONTRACT> M_CONTRACT { get; set; }
        public virtual DbSet<M_GROUP> M_GROUP { get; set; }
        public virtual DbSet<M_ICON> M_ICON { get; set; }
        public virtual DbSet<M_MODULE> M_MODULE { get; set; }
        public virtual DbSet<M_ROLE> M_ROLE { get; set; }
        public virtual DbSet<M_SERVER> M_SERVER { get; set; }
        public virtual DbSet<M_SETTING> M_SETTING { get; set; }
        public virtual DbSet<M_THEME> M_THEME { get; set; }
        public virtual DbSet<M_TOKEN> M_TOKEN { get; set; }
        public virtual DbSet<M_USER> M_USER { get; set; }
        public virtual DbSet<M_VENDOR> M_VENDOR { get; set; }
        public virtual DbSet<MESSAGE> MESSAGEs { get; set; }
        public virtual DbSet<NOTIFICATION> NOTIFICATIONs { get; set; }
    }
}
