//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMS.Context.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_IIS
    {
        public Nullable<decimal> SCWIN32STATUS { get; set; }
        public Nullable<decimal> SCSUBSTATUS { get; set; }
        public Nullable<decimal> SCSTATUS { get; set; }
        public string CSHOST { get; set; }
        public string CSREFERER { get; set; }
        public string CSCOOKIE { get; set; }
        public string CSUSERAGENT { get; set; }
        public string CSVERSION { get; set; }
        public string CIP { get; set; }
        public string CSUSERNAME { get; set; }
        public Nullable<decimal> SPORT { get; set; }
        public string CSURISTEM { get; set; }
        public string CSURIQUERY { get; set; }
        public string SIP { get; set; }
        public string SCOMPUTERNAME { get; set; }
        public string SSITENAME { get; set; }
        public Nullable<System.DateTime> DATETIMEEVENT { get; set; }
        public Nullable<decimal> CSBYTES { get; set; }
        public Nullable<decimal> TIMETAKEN { get; set; }
        public Nullable<decimal> TOTALTAKEN { get; set; }
        public string CSMETHOD { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string LOG_IPSERVER { get; set; }
        public decimal LOG_ID { get; set; }
        public Nullable<decimal> LOG_YEAR { get; set; }
        public Nullable<decimal> LOG_MONTH { get; set; }
    }
}
