//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMS.Context.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_APP
    {
        public decimal LOG_ID { get; set; }
        public string LOG_TITLE { get; set; }
        public string LOG_CONTENT { get; set; }
        public string BROWSER { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    }
}
