//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMS.Context.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ACCESS
    {
        public decimal MODULE_ID { get; set; }
        public decimal GROUP_ID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    
        public virtual M_GROUP M_GROUP { get; set; }
        public virtual M_MODULE M_MODULE { get; set; }
    }
}
