//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMS.Context.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CONTRACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_CONTRACT()
        {
            this.LOG_PERSO = new HashSet<LOG_PERSO>();
            this.LOG_PERSO_COUNT = new HashSet<LOG_PERSO_COUNT>();
        }
    
        public decimal CONTRACT_ID { get; set; }
        public string CONTRACT_NAME { get; set; }
        public string CONTRACT_DESC { get; set; }
        public string ATTACHMENT { get; set; }
        public Nullable<System.DateTime> PERIOD_START { get; set; }
        public Nullable<System.DateTime> PERIOD_END { get; set; }
        public Nullable<decimal> QUOTA { get; set; }
        public Nullable<decimal> VENDOR_ID { get; set; }
        public Nullable<decimal> ISACTIVE { get; set; }
        public Nullable<decimal> ISDELETE { get; set; }
        public Nullable<decimal> CREATEBY { get; set; }
        public Nullable<decimal> UPDATEBY { get; set; }
        public Nullable<decimal> DELETEBY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<System.DateTime> DELETEDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_PERSO> LOG_PERSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_PERSO_COUNT> LOG_PERSO_COUNT { get; set; }
        public virtual M_VENDOR M_VENDOR { get; set; }
    }
}
