//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMS.Context.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_SETTING
    {
        public decimal USER_ID { get; set; }
        public Nullable<decimal> GRID_PAGESIZE { get; set; }
        public Nullable<decimal> GRID_THEME { get; set; }
        public Nullable<decimal> GRID_ZEBRACOLOR { get; set; }
        public Nullable<decimal> GRID_WRAP_COLUMN { get; set; }
        public Nullable<decimal> GRID_WRAP_CELL { get; set; }
        public Nullable<decimal> GRID_SHOWFILTERROW { get; set; }
        public Nullable<decimal> GRID_SHOWFILTERBAR { get; set; }
        public Nullable<decimal> GRID_SELECTBYROW { get; set; }
        public Nullable<decimal> GRID_FOCUSEROW { get; set; }
        public Nullable<decimal> GRID_ELLIPSIS { get; set; }
        public Nullable<decimal> GRID_SHOWFOOTER { get; set; }
        public Nullable<decimal> GRID_RESPONSIVE { get; set; }
    
        public virtual M_USER M_USER { get; set; }
    }
}
