//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMS.Context.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_TOKEN
    {
        public decimal TOKEN_ID { get; set; }
        public Nullable<decimal> USER_ID { get; set; }
        public string TOKEN { get; set; }
        public Nullable<decimal> ISACTIVE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    
        public virtual M_USER M_USER { get; set; }
    }
}
