//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMS.Context.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE
    {
        public Nullable<decimal> USER_FROM { get; set; }
        public Nullable<decimal> USER_TO { get; set; }
        public Nullable<decimal> ISREAD { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string MESSAGE_CONTENT { get; set; }
        public decimal MESSAGE_ID { get; set; }
    
        public virtual M_USER M_USER { get; set; }
        public virtual M_USER M_USER1 { get; set; }
    }
}
