//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMS.Context.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION
    {
        public decimal NOTIF_ID { get; set; }
        public string NOTIF_TITLE { get; set; }
        public string NOTIF_MESSAGE { get; set; }
        public Nullable<decimal> NOTIF_TYPE { get; set; }
        public Nullable<decimal> TO_USER_ID { get; set; }
        public Nullable<decimal> ISREAD { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string URL { get; set; }
    
        public virtual M_USER M_USER { get; set; }
    }
}
